### ISSUE TITLE
Open connections keep increase even chain is closed

### ISSUE THREAD

**Issue by xpader** [orlv/tiny-proxy-chain#2]
I have a program start running several months, it make fixed port proxy to dynamic remote proxy through tiny-proxy-chain, and close proxy chain after some minutes.

Recently I found that node open connection keep increase, and trigger "Too many open files in system" error.

When I use command `lsof -n -p pid` , it show too much ESTABLISHED and CLOSE_WAIT connections.

Another program same like this program running, only different is this program has no such "proxy chain" mechanism, and this program connections count is very stable.

Anyway to fix this?

**Comment by orlv** [comment]
Hi. Checked lsof on my server, found the same issue.
I will try to solve the problem as soon as possible.

**Comment by orlv** [comment]
Hi. Leaks are fixed now. 
No more CLOSE_WAIT connections. 

Try version 1.6.0.

**Comment by xpader** [comment]
Ok, I've updated the program, and I'll take a look.

**Comment by xpader** [comment]
After several days of observation, the number of open files has been somewhat improved, but still not close all.
The number just increase slowly than before.
